/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Time range string in HH:MM-HH:MM format (24h).
 */
export type OpenHoursRange = string;
/**
 * Enumeration of possible task states.
 */
export type TaskStatus = 'Pending' | 'Done' | 'Deleted';

export interface TunnelAlgorithmTestCaseSchema {
  /**
   * Name of the scenario
   */
  name: string;
  /**
   * Comprehensive narrative explaining the test purpose
   */
  description: string;
  /**
   * The starting state of the system before any steps are executed.
   */
  initial_state: {
    /**
     * ISO 8601 timestamp with strictly numeric offset (e.g. +00:00)
     */
    current_time: string;
    /**
     * Offset in seconds from UTC. Defines the global timezone context for the test case. Defaults to 0 (UTC).
     */
    timezone_offset?: number;
    /**
     * List of Place definitions available in the test scenario.
     */
    places?: Place[];
    /**
     * List of input Tasks defining the initial structure and state.
     */
    tasks: TaskInput[];
    [k: string]: unknown;
  };
  /**
   * Sequence of mutation and assertion steps to execute.
   */
  steps: Step[];
  [k: string]: unknown;
}
/**
 * Represents a Context (Location + Time) constraint.
 */
export interface Place {
  /**
   * Unique Identifier for the Place. 'Anywhere' is reserved and cannot be used.
   */
  id: string;
  hours?: OpenHours;
  /**
   * List of Place IDs included within this place context (one-level deep).
   */
  included_places?: string[];
  [k: string]: unknown;
}
/**
 * Defines the operating hours for the place.
 */
export interface OpenHours {
  /**
   * Operating mode: 'always_open', 'always_closed', or 'custom'.
   */
  mode: 'always_open' | 'always_closed' | 'custom';
  /**
   * Weekly schedule mapping days to time ranges (required if mode is 'custom').
   */
  schedule?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^(Sun|Mon|Tue|Wed|Thu|Fri|Sat)$".
     */
    [k: string]: OpenHoursRange[];
  };
}
/**
 * Input record for a Task, combining immutable spec and mutable state.
 */
export interface TaskInput {
  /**
   * Unique Identifier (Primary Key).
   */
  id: string;
  /**
   * Recursive list of child tasks.
   */
  children?: TaskInput[];
  /**
   * Display name or title of the task.
   */
  title?: string;
  /**
   * (0.0–1.0) Importance relative to parent. Set by user.
   */
  importance?: number;
  /**
   * Current state ({ Pending, Done, Deleted }). Used to derive IsPending.
   */
  status?: 'Pending' | 'Done' | 'Deleted';
  /**
   * Current total of decayed credit history for this task/subtree.
   */
  credits?: number;
  /**
   * Timestamp of last credit modification (t0 for decay calculations).
   */
  credits_timestamp?: string | undefined;
  /**
   * Target allocation value (only valid for Root Goals).
   */
  desired_credits?: number;
  /**
   * Due Date for the task.
   */
  due_date?: string | undefined;
  /**
   * Link to the Place this task belongs to. Inherits from Parent if Null.
   */
  place_id?: string | undefined;
  /**
   * Lead time in seconds. Defaults to 7 days (604800).
   */
  lead_time_seconds?: number;
  /**
   * If true, children tasks are strictly ordered and blocked sequentially.
   */
  is_sequential?: boolean;
  [k: string]: unknown;
}
/**
 * A single stage in the test scenario involving mutations followed by assertions.
 */
export interface Step {
  /**
   * Name of the step for reporting.
   */
  name: string;
  /**
   * The active View Filter context for this step (e.g. 'All Places', 'Home'). Defaults to 'All Places'.
   */
  view_filter?: string;
  /**
   * State changes to apply before verification.
   */
  mutation?: {
    /**
     * Seconds to advance the global clock.
     */
    advance_time_seconds?: number;
    /**
     * Map of TaskID to new Credit values (simulating manual adjustment).
     */
    update_credits?: {
      [k: string]: number;
    };
    /**
     * List of updates to specific tasks (Status, Credits, etc.).
     */
    task_updates?: {
      id: string;
      status?: TaskStatus;
      credits?: number;
      desired_credits?: number;
      importance?: number;
      due_date?: string | undefined;
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  };
  /**
   * Exhaustive list of visible task IDs in strict order.
   */
  expected_order: string[];
  /**
   * List of partial task objects to verify specific state or computed properties.
   */
  expected_props?: {
    id: string;
    score?: number;
    effective_credits?: number;
    normalized_importance?: number;
    is_blocked?: boolean;
    is_visible?: boolean;
    is_ready?: boolean;
    is_open?: boolean;
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
