ls:
  .*: kebab-case
  .cjs: regex:use-js-instead
  .mjs: regex:use-js-instead
  .md: kebab-case | SCREAMING_SNAKE_CASE

ignore:
  - .gemini
  - .git
  - .github
  - .husky
  - .moon
  - .specify
  - .turbo
  - .vscode
  - "**/__screenshots__"
  - "**/build"
  - "**/coverage"
  - "**/dev-dist"
  - "**/dist"
  - "**/node_modules"
  - "**/test-results"
