packages:
  - apps/*
  - docs
  - scripts
  - crates/tasklens-ui

catalogs:
  default:
    "@automerge/automerge-repo": 2.5.1
    "@automerge/automerge-repo-network-websocket": 2.5.1
    "@automerge/automerge-repo-storage-nodefs": 2.5.1
    "@biomejs/biome": ^2.3.11
    "@commitlint/cli": ^20.3.0
    "@commitlint/types": ^20.3.1
    "@playwright/test": ^1.57.0
    "@types/js-yaml": 4.0.9
    "@types/node": 25.0.9

    glob: ^13.0.0
    husky: ^9.1.7
    js-yaml: 4.1.1
    knip: ^5.80.2
    minimatch: ^10.1.1
    prettier: ^3.4.2
    syncpack: ^13.0.2
    tsx: ^4.21.0
    typescript: 5.9.3

    vitest: 4.0.17
    wait-port: ^1.1.0
    ws: ^8.19.0
    zod: ^4.3.5

ignoredBuiltDependencies:
  - "@swc/core"
  - cbor-extract
  - unrs-resolver

onlyBuiltDependencies:
  - esbuild
