packages:
  - apps/*
  - packages/*
  - docs
  - scripts

catalogs:
  default:
    '@automerge/automerge': ^3.2.1
    '@automerge/automerge-repo': ^2.5.1
    '@automerge/automerge-repo-network-websocket': ^2.5.1
    '@automerge/automerge-repo-react-hooks': ^2.5.1
    '@automerge/automerge-repo-storage-indexeddb': ^2.5.1
    '@biomejs/biome': ^2.3.11
    '@commitlint/cli': ^20.2.0
    '@commitlint/types': ^20.2.0
    '@eslint/js': ^9.39.2
    '@ls-lint/ls-lint': ^2.3.1
    '@mantine/core': 8.3.10
    '@mantine/dates': 8.3.10
    '@mantine/form': 8.3.10
    '@mantine/hooks': 8.3.10
    '@mantine/notifications': ^8.3.10
    '@playwright/test': ^1.57.0
    '@reduxjs/toolkit': ^2.5.0
    '@tabler/icons-react': ^3.36.0
    '@testing-library/react': ^16.3.1
    '@testing-library/user-event': ^14.6.1
    '@types/js-yaml': ^4.0.9
    '@types/minimist': ^1.2.5
    '@types/node': 25.0.3
    '@types/react': ^19.2.7
    '@types/react-dom': ^19.2.3
    '@vitejs/plugin-react': ^5.1.1
    '@vitest/browser': ^4.0.16
    '@vitest/browser-playwright': ^4.0.16
    '@vitest/coverage-v8': ^4.0.16
    ajv: ^8.17.1
    ajv-formats: ^3.0.1
    dayjs: ^1.11.19
    eslint: ^9.39.2
    eslint-plugin-import-x: ^4.16.1
    glob: ^11.0.0
    globals: ^16.5.0
    knip: ^5.78.0
    lint-staged: ^16.2.7
    husky: ^9.1.7
    js-yaml: ^4.1.1
    minimatch: ^9.0.5
    minimist: ^1.2.8
    json-schema-to-typescript: ^15.0.4
    playwright-bdd: ^8.4.2
    postcss: 8.5.6
    prettier: ^3.4.2
    postcss-preset-mantine: 1.18.0
    postcss-simple-vars: 7.0.1
    react: ^19.2.3
    react-dom: ^19.2.3
    react-redux: 9.2.0
    syncpack: ^13.0.2
    tsx: ^4.21.0
    turbo: ^2.7.1
    typescript: 5.9.3
    typescript-eslint: ^8.51.0
    vite: ^7.2.4
    vite-plugin-pwa: ^1.2.0
    vite-plugin-top-level-await: ^1.6.0
    vite-plugin-wasm: ^3.5.0
    vitest: 4.0.16
    workbox-window: ^7.4.0
    zod: ^4.2.1

ignoredBuiltDependencies:
  - '@swc/core'
  - cbor-extract
  - unrs-resolver

onlyBuiltDependencies:
  - esbuild
