packages:
  - apps/*
  - docs
  - scripts
  - crates/tasklens-ui

catalogs:
  default:
    "@automerge/automerge-repo": 2.5.1
    "@automerge/automerge-repo-network-websocket": 2.5.1
    "@automerge/automerge-repo-storage-nodefs": 2.5.1
    "@biomejs/biome": 2.3.15
    "@commitlint/cli": 20.4.1
    "@commitlint/types": 20.4.0
    "@axe-core/playwright": ^4.11.0
    "@playwright/test": 1.58.2
    "@types/node": 25.2.2

    glob: 13.0.1
    husky: ^9.1.7
    knip: 5.82.1
    prettier: ^3.4.2
    serve: ^14.2.4
    syncpack: ^13.0.2
    typescript: 5.9.3

    vitest: 4.0.18
    wait-port: ^1.1.0
    ws: ^8.19.0
    js-yaml: ^4.1.1
    "@types/js-yaml": ^4.0.9

ignoredBuiltDependencies:
  - "@swc/core"
  - cbor-extract
  - unrs-resolver

onlyBuiltDependencies:
  - esbuild
