// AUTOGENERATED Components module
#![allow(unreachable_pub)]
#![allow(dead_code)]
pub mod badge;
pub mod button;
pub mod card;
pub mod checkbox;
pub mod collapsible;
pub mod dialog;
pub mod input;
pub mod label;
pub mod navbar;
pub mod popover;
pub mod progress;
pub mod select;
pub mod slider;
pub mod switch;
pub mod textarea;
pub mod toggle;
pub mod toggle_group;
