// AUTOGENERATED Components module
#![allow(unreachable_pub)]
#![allow(dead_code)]
pub mod badge;
pub mod button;
pub mod card;
pub mod checkbox;
pub mod collapsible;
pub mod dialog;
pub mod input;
pub mod select;
